### ISSUE TITLE
CREATE - Entidad de perfil del usuario-Backend

### ISSUE THREAD

**Issue by Siuss** [Siuss/gamerly-backend#2]
**DEFINIR PERFIL de Usuario** Dominio del Backend, comunicación para la Persistencia
 
> Teniendo presente todo el dominio de la solución (reseñas, amistades, comunidades, etc.):

**_COMO_** desarrollador **_QUIERO_** crear BB.DD. la entidad 'Perfil' de Usuario **_PARA_** persistir, consultar los datos asociados a cada entidad:

> **_COMO_** usuario **_QUIERO_**  recuperar mi propia información propia y de otros usuarios **_PARA_**, en el primer caso administrar mis propios datos (leer, modificar, eliminar); y en el segundo, para filtrar y buscar otros Usuarios para leerlos.

**Átomos que incluye**:

- [x] Entindad **Perfil**: campos necesarios:

> - [x] nombre
> - [x] foto
> - [x] edad
> - [x] sexo
> - [x] juegos preferidos
> - [x] dias preferido
> - [x] horarios preferido

Todo Usuario tiene Perfil

<details><summary>Imágen de la documentación</summary>
<p>
![Image](https://github.com/Siuss/gamerly-backend/assets/30749611/8f0589cb-0bb0-470f-a781-e6f85cea4571)
</p>
</details>

Actividad vinculada a Perfil:
- [x] #18

**Comment by rodripavon97** [comment]
que datos va tener.
nombre
edad
sexo
juegos preferidos
dias preferido
horarios preferido

**Comment by rodripavon97** [comment]
despues se reabre para usar el rest
