### ISSUE TITLE
Hacer investigación para la imprementacion de jwt en el backend

### ISSUE THREAD

**Issue by rodripavon97** [Siuss/gamerly-backend#53]
por temas de seguridad mandaría un token del usuario al inicial sesion y mantener la sesion sin mostrar datos sensibles. Esto pasa el sprint 5

**Comment by veronicacarbonelli** [comment]
[Material para implementar JWT.pdf](https://github.com/user-attachments/files/15743700/Material.para.implementar.JWT.pdf)
