### ISSUE TITLE
CREATE - Endpoints para crear resenias

### ISSUE THREAD

**Issue by Siuss** [Siuss/gamerly-backend#6]
****CONTROLERS** escucha al frontend y conección con el dominio de Perfiles
 
**_COMO_** desarrollador **_QUIERO_** crear los EndPoint 'Resenias' para su crearción **_PARA_** persistir, conultar los datos asociados a cada entidad, modificar:

> **_COMO_** usuario **_QUIERO_**  generar reseñas sobre otro usuario **_PARA_**, puntuar, ver puntaciónes propias y otros jugadores.

**Átomos que incluye**:

## EndPoints **Reseñas**: campos necesarios.

  > - [x] Endpoint Creación: #38 
> - [x] Endpoint Consultas (Leer): #39 

Todo Usuario tiene Perfil

<details><summary>Imagen de la documentación</summary>
<p>
Proximamente
</p>
</details>

<details><summary>Detalles actualización</summary>
<p>

> > - [ ] ~Modificación~ (no queda cubierto en esta tarea).
> > - [ ] ~Eliminación~ (no queda cubierto en esta tarea).

</p>
</details>

**Comment by rodripavon97** [comment]
@julii0m te dejo el issue #38
