### ISSUE TITLE
Crear conjunto de dias y horarios

### ISSUE THREAD

**Issue by alangomez900** [Siuss/gamerly-backend#87]
El _frontend_ esta formateado en una tabla de días y horarios (ej.: Viernes a la noche, Sábado a la mañana), hay que implementarlo de esa manera en el _backend_. Ya **existen los días y horarios por separado**, hay que unirlos en una clase.

> **COMO** _desarrollador_ **QUIERO** _implementar la Clase, Entidad y _"refactor"__ **PARA** _establecer relaciones del Usuario, sus días y horarios de juego_.

**COMO** _usuario_ **QUIERO** _establecer y actualizar mis preferencias de días y horarios_ **PARA** _establecer relaciones del Usuario, sus días y horarios de juego_.

1. > - [ ] Clase `días_horarios`, dominio. 
2. > - [ ] Servicio y Entidad `usuario_días_horarios_preferidos`
3. > - [ ]  Refactor de referencia en _backend_.

<details><summary>Diseño de la BB.DD.</summary>
<p>

![Image](https://github.com/Siuss/gamerly-backend/assets/30749611/8a532fdd-e453-4f55-8acc-3ea87241aaec)

</p>
</details> 

<details><summary>Propuesta **Clase** tentativa de solución</summary>
<p>

```
import jakarta.persistence.*

import com.gamerly.projectgamerly.domain.Usuario
import com.gamerly.projectgamerly.domain.HorariosFavoritos
import com.gamerly.projectgamerly.resources.enum.DiaDeLaSemana

@Entity
@Table(name = "diasHorarios")
data class MomentoJuego(

    @Enumerated(EnumType.STRING)
    val diaDeLaSemana: DiaDeLaSemana,

    @Enumerated(EnumType.STRING)
    val horarioFavorito: HorariosFavoritos

    @ManyToOne
    val usuario: Usuario, // Relación con la entidad Usuario

) {
          @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        val id: Long = 0,
  }

```

</p>
</details>

**Comment by Siuss** [comment]
@rodripavon97 tengo una propuesta de Clase, quiero saber si voy bien encaminado. Creo que se queja que no tengo creado el servicio, ¿puede ser? (Sé que lo tengo que crear, pero me sugiero creármelo el IntelliJ).

@alangomez900 ¿Cómo lo ves?

**Comment by rodripavon97** [comment]
No será el tema repo para guardar la tabla en el bootstrap?

**Comment by rodripavon97** [comment]
Porque si no está guardado en el bootstrap y no apunta un repo no lo crea por lo que tengo entendido

**Comment by Siuss** [comment]
Buenísimo. Lo reviso. Gracias @rodripavon97 

Otro tema: Días y horarios, ¿Es necesario que estén concatenados? Por ahora los planteo como 2 campos distintos de una misma tabla. ¿Está bien?

**Comment by rodripavon97** [comment]
Si para mí está bien que estén en la misma tabla, que opinas @alangomez900

**Comment by Siuss** [comment]
@rodripavon97 @alangomez900 Se actualizó el dominio para 'DíasHorariosPreferidos' y incluyó en el formato 'UsuarioDetalleDTO'.

Por lo que, tener una lista de días por un lado, y por otra una lista de hroarios, no es tan correcto. Con lo que quedan 2 opciones:

- Que se haga una combinatoria entra ambas listas ( generando datos extras ).

- Ó, que se maneje una estructura, donde por cada día se traiga la lista de horarios
(ejemplo, puede ser un diccionario ` { "DIA" : [ "HORARIO1", "HORARIO2" ] } ` ).

- [ ] #87  -> [Rama 87](https://github.com/Siuss/gamerly-backend/tree/87-crear-conjunto-de-dias-y-horarios)

**Comment by Siuss** [comment]
> [@rodripavon97](https://github.com/rodripavon97) [@alangomez900](https://github.com/alangomez900) Se actualizó el dominio para 'DíasHorariosPreferidos' y incluyó en el formato 'UsuarioDetalleDTO'.
> 
> Por lo que, tener una lista de días por un lado, y por otra una lista de hroarios, no es tan correcto. Con lo que quedan 2 opciones:
> 
> * Que se haga una combinatoria entra ambas listas ( generando datos extras ).
> * Ó, que se maneje una estructura, donde por cada día se traiga la lista de horarios
>   (ejemplo, puede ser un diccionario `{ "DIA" : [ "HORARIO1", "HORARIO2" ] }` ).
> * [ ]  [Crear conjunto de dias y horarios #87](https://github.com/Siuss/gamerly-backend/issues/87)  -> [Rama 87](https://github.com/Siuss/gamerly-backend/tree/87-crear-conjunto-de-dias-y-horarios)

### Se avanza por la opción que **combina un elemento de cada lista según su igual índice** (por lo que ambas lista deben tener el mismo tamañan). -> 5bc6d79208004eec59f55bfbd1e5509d9b9dbbe1

**Comment by Siuss** [comment]
## Se genera [PR 92 ](https://github.com/Siuss/gamerly-backend/pull/92)
